INSERT INTO MUSIC (artistname,albumname,numbersold,cost) values ('Mozart','Greatest Hits',100000,10);
INSERT INTO MUSIC (artistname,albumname,numbersold,cost) values ('Taylor Swift','Fearless',2300000,15);
INSERT INTO MUSIC (artistname,albumname,numbersold,cost) values ('Black Sabbath','Paranoid',534000,12);
INSERT INTO MUSIC (artistname,albumname,numbersold,cost) values ('Katy Perry','Prism',800000,16);
INSERT INTO MUSIC (artistname,albumname,numbersold,cost) values ('Katy Perry','Teenage Dream',750000,14);